# Generated by Django 5.1.1 on 2024-09-23 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mainapp', '0002_player'),
    ]

    operations = [
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_played', models.DateField(blank=True, null=True)),
                ('round_type', models.CharField(blank=True, max_length=30, null=True)),
                ('weather', models.CharField(blank=True, max_length=50, null=True)),
                ('comments', models.CharField(blank=True, max_length=300, null=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='mainapp.course')),
                ('player', models.ManyToManyField(blank=True, related_name='rounds', to='mainapp.player')),
                ('tee_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='mainapp.tee')),
            ],
        ),
        migrations.CreateModel(
            name='RoundStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('par', models.IntegerField()),
                ('score', models.IntegerField()),
                ('fairway', models.CharField(blank=True, choices=[('wayleft', 'Way Left'), ('left', 'Left'), ('hit', 'Hit'), ('right', 'Way Left'), ('wayright', 'Way Right'), ('na', 'na')], max_length=50, null=True)),
                ('drivedistance', models.IntegerField(blank=True, null=True)),
                ('green', models.CharField(blank=True, choices=[('longleft', 'Long Left'), ('long', 'Long'), ('longright', 'Long Right'), ('left', 'Left'), ('hit', 'Hit'), ('right', 'Right'), ('shortleft', 'Short Left'), ('short', 'Short'), ('shortright', 'Short Right'), ('notreach', 'Could Not Reach'), ('na', 'na')], max_length=50, null=True)),
                ('putts', models.IntegerField(blank=True, null=True)),
                ('firstputtdistance', models.IntegerField(blank=True, null=True)),
                ('updown', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('na', 'na')], max_length=50, null=True)),
                ('sandsave', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('na', 'na')], max_length=50, null=True)),
                ('penalties', models.IntegerField(blank=True, null=True)),
                ('hole_number', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='round_stats', to='mainapp.hole')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='round_stats', to='roundapp.round')),
            ],
        ),
    ]
