# Generated by Django 5.1.1 on 2024-09-24 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roundapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='round_type',
            field=models.CharField(blank=True, choices=[('regular', 'Regular'), ('practice', 'Practice'), ('tournament', 'Tournament')], max_length=30, null=True),
        ),
    ]
