# Generated by Django 5.1.1 on 2024-09-24 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roundapp', '0002_alter_round_round_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='wind',
            field=models.CharField(blank=True, choices=[('nowind', 'No Wind'), ('lightwind', 'Light Wind'), ('strongwind', 'Strong Wind')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='round',
            name='weather',
            field=models.CharField(blank=True, choices=[('sunny', 'Sunny'), ('overcast', 'Overcast'), ('rain', 'Rain')], max_length=50, null=True),
        ),
    ]
