# Generated by Django 5.1.1 on 2024-09-24 02:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_player'),
        ('roundapp', '0003_round_wind_alter_round_weather'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='round',
            name='player',
        ),
        migrations.AddField(
            model_name='round',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='mainapp.player'),
        ),
    ]
