# Generated by Django 5.1.1 on 2024-10-07 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roundapp', '0006_alter_round_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
    ]
